# Example Praefect configuration file
# # TCP address to listen on
# listen_addr = "127.0.0.1:2305"

# # Praefect can listen on a socket when placed on the same machine as all clients
socket_path = "/services/sockets/praefect.socket"
# # Praefect will only replicate whitelisted repositories
# # Optional: export metrics via Prometheus
#prometheus_listen_addr = "127.0.0.1:10101"

# # You can optionally configure Praefect to output JSON-formatted log messages to stdout
[logging]
format = "json"
# # Optional: Set log level to only log entries with that severity or above
# # One of, in order: debug, info, warn, errror, fatal, panic
# # Defaults to "info"
#   level = "warn"

[failover]
read_only_after_failover = false # favors availability over consistency

[[virtual_storage]]
name = 'default'

# # One or more Gitaly servers need to be configured to be managed. The names
# of each server are used to link multiple nodes, or `gitaly_server`s together
# as shard. listen_addr should be unique for all nodes.
# Requires the protocol to be defined, e.g. tcp://host.tld:1234


[[virtual_storage.node]]
  storage = "praefect-internal-0"
  address = "unix:/services/sockets/gitaly-praefect-0.socket"


[database]
user = ${DATABASE_USERNAME:-postgres}
host = ${DATABASE_HOST:-pg}
port = ${DATABASE_PORT:-5432}
password=${DATABASE_PASSWORD}
dbname = "gisia_praefect_prd"
sslmode = "disable"

