production: &base

  # Gitaly settings
  gitaly:
    # Default Gitaly authentication token. Can be overridden per storage. Can
    # be left blank when Gitaly is running locally on a Unix socket, which
    # is the normal way to deploy Gitaly.
    token:

  #
  # 4. Advanced settings
  # ==========================

  ## Repositories settings
  repositories:
    # Paths where repositories can be stored. Give the canonicalized absolute pathname.
    # IMPORTANT: None of the path components may be symlink, because
    # gitlab-shell invokes Dir.pwd inside the repository path and that results
    # real path not the symlink.
    storages: # You must have at least a `default` storage path.
      default:
        gitaly_address: unix:/services/sockets/praefect.socket

  ## GitLab Shell settings
  gitlab_shell:
    path: /gisia/coms/bin/gitlab-shells
    authorized_keys_file: /gisia/coms/data/ssh/authorized_keys

    # Git over HTTP
    upload_pack: true
    receive_pack: true

    ssh_port: 2626
    ssh_host: ${GISIA_HOST}
  asset_proxy:
    enabled: false

  ## Build Artifacts
  artifacts:
    enabled: true
    object_store:
      enabled: false
      remote_directory: artifacts
      direct_upload: true
      connection:
        provider: AWS
        aws_access_key_id: minio
        aws_secret_access_key: gdk-minio
        region: gdk
        endpoint: 'https://example.com:9000'
        path_style: true

  ## Merge request external diff storage
  external_diffs:
    enabled: false
    object_store:
      enabled: false
      remote_directory: external-diffs
      direct_upload: true
      connection:
        provider: AWS
        aws_access_key_id: minio
        aws_secret_access_key: gdk-minio
        region: gdk
        endpoint: 'https://example.com:9000'
        path_style: true
  ## Git LFS
  lfs:
    enabled: true
    object_store:
      enabled: false
      remote_directory: lfs-objects
      direct_upload: true
      connection:
        provider: AWS
        aws_access_key_id: minio
        aws_secret_access_key: gdk-minio
        region: gdk
        endpoint: 'https://example.com:9000'
        path_style: true

  ## Uploads (attachments, avatars, etc...)
  uploads:
    # The location where uploads objects are stored (default: public/).
    # storage_path: public/
    # base_dir: uploads/-/system
    object_store:
      enabled: false
      remote_directory: uploads
      direct_upload: true
      connection:
        provider: AWS
        aws_access_key_id: minio
        aws_secret_access_key: gdk-minio
        region: gdk
        endpoint: 'https://gisa.dev:9000'
        path_style: true
  ## Backup settings
  backup:
    # not enabled
    path: "/gisia/coms/backup"   # Relative paths are relative to Rails.root (default: tmp/backups/)
    # gitaly_backup_path: gitaly/_build/bin/gitaly-backup
